### ISSUE TITLE
IDE files inside repository

### ISSUE THREAD

**Issue by danmarsden** [maxwell-hgr/moodle-local_webcourse#7]
probably good to delete the .idea folder from your github repo and maybe consider adding it to your local .gitignore configuration to prevent being sent through to git.

**Comment by maxwell-hgr** [comment]
Hey! I've made the corrections, and everything seems to be working fine now. Thank you so much! I'm a beginner developer in Moodle, so what are the next steps?

**Comment by danmarsden** [comment]
Hey @maxwell-hgr - I haven't quite finished the review yet - I had 10min last night so just pulled this one out of the queue and got started - great to see you've already made some improvements - hopefully I'll get to finishing the review in the next couple of days!
