### ISSUE TITLE
create_course_custom doesn't exist

### ISSUE THREAD

**Issue by danmarsden** [maxwell-hgr/moodle-local_webcourse#9]
https://github.com/maxwell-hgr/moodle-local_webcourse/blob/master/index.php#L90

I suspect it's a function you renamed to meet frankenstyle guidelines but didn't update where it was being called?

**Comment by danmarsden** [comment]
also - same file "generate_csv"
https://github.com/maxwell-hgr/moodle-local_webcourse/blob/master/index.php#L134

**Comment by maxwell-hgr** [comment]
@danmarsden, thank you so much for your detailed reports! I’ve made the corrections and tested the plugin on my local Moodle, and everything is working perfectly now. I initially thought that access.php was required for Moodle to determine user access to the plugin—but I guess I was wrong! Haha. I really appreciate your help. 😊

However, I’ve run into a small issue. While the plugin runs correctly, the Moodle Plugin CI test shows a warning saying the login check is missing. When I try adding require_login() or require_admin() to the lib.php file, the plugin stops working. Do you have any idea why this might be happening? Could you recommend any documentation or resources to help me better understand and fix this?

Thanks so much for your time and support!

FILE: /home/runner/work/moodle-local_webcourse/moodle-local_webcourse/moodle/local/webcourse/lib.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------
 27 | WARNING | Expected login check (require_login, require_course_login, require_admin, admin_externalpage_setup) following
    |         | config inclusion. None found. (moodle.Files.RequireLogin.Missing)

**Comment by danmarsden** [comment]
you just need to delete line 27:
https://github.com/maxwell-hgr/moodle-local_webcourse/blob/master/lib.php#L27

the config.php is already included by the time someone tries to load the lib.php file.

**Comment by maxwell-hgr** [comment]
When I delete this line and try to access the plugin, the screen goes white, I don't have any debug messages or in the console.
And then if I add it I need to check the login and it ends up giving a warning in the test.

**Comment by danmarsden** [comment]
white screen usually means there's a php error on the page.

try deleting that config.php include (line 27) again and then also add the following code to your config.php file to increase the debug level on the site 

```
@error_reporting(1023);  // NOT FOR PRODUCTION SERVERS!
@ini_set('display_errors', '1'); // NOT FOR PRODUCTION SERVERS!
$CFG->debug = 32767;  // DEBUG_DEVELOPER // NOT FOR PRODUCTION SERVERS!
$CFG->debugdisplay = true;   // NOT FOR PRODUCTION SERVERS!
```

Then when you reload the page again - you should see the actual php error rather than a white screen.

**Comment by maxwell-hgr** [comment]
I followed your instructions and made a few additional tweaks. It's finally working and passing all the tests.
Really appreciate your help!
I've uploaded the updated version to Moodle as well. Hopefully, everything is good to go now!
